services:
  # s3
  s3:
    image: adobe/s3mock:latest
    environment:
      initialBuckets: test-bucket
      root: /data
      debug: "true"
      trace: "false"
      retainFileOnExit: "false"
    ports:
      - "9090:9090"
      - "9191:9191"
    volumes:
      - "./s3/data:/data"
  # gs
  gs:
    image: fsouza/fake-gcs-server:latest
    ports:
      - "4443:4443"
      - "8000:8000"
    volumes:
      - "./gs/storage:/storage"
    command: --scheme http --port 8000 --public-host localhost:8000 --filesystem-root /storage
  # sms
  localstack:
    image: localstack/localstack:latest
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1
      DISABLE_CORS_CHECKS: 1
    ports:
      - "4566:4566"
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "./localstack/data:/var/lib/localstack"